### ISSUE TITLE
Update to latest Django 4.0x

### ISSUE THREAD

**Issue by tordans** [FixMyBerlin/fixmy.platform#636] opened 2022-01-26 16:11 UTC
Goal: Test and if possible use the newest Django version.

Links:

- Internal discussion and more links https://fixmy.slack.com/archives/CA5SQMGRK/p1643026510002400
- Current Django Version https://github.com/FixMyBerlin/fixmy.platform/blob/master/requirements.txt

Steps

- Dev: Test locally first
- Staging: Merge in develop will trigger a deploy on Heroku and Lightsail for Staging-Testing
- Then: Production

**Comment by ohrie** [comment] 2022-04-05 08:51
We need to wait at least for django-markdownx , since it's not yet compatible with django 4. Maybe I will try the version 4 beta of it: https://github.com/neutronX/django-markdownx/releases/tag/v4.0.0-beta.1

**Comment by ohrie** [comment] 2022-04-05 10:17
Deployed successfully on Heroku on all three products. But there seem to be some exceptions in the log. But I don't know if they are caused by Django 4.

**Comment by ohrie** [comment] 2022-04-05 10:19
I've updated the Python runtime from 3.8 to 3.9.

**Comment by ohrie** [comment] 2022-04-15 08:50
When changing the own password , HTTP 406 error is occuring:
https://stackoverflow.com/questions/30903951/django-doesnt-parse-a-custom-http-accept-header

**Comment by ohrie** [comment] 2022-06-20 12:29
I again updated to Django 4.0.5. The Change password error still exists and needs to be resolved otherwise. It is most probably caused by djangorestframework/djoser.

Therefore I would close this issue, since I've tested most of the functionality and works for me on staging.

**Closed by ohrie** 2022-06-20 12:29 UTC
Labels: dependencies
